import * as Factory from 'factory.ts';
import type { Property } from './generated/types';
import { RequiredBaseEntity } from './types';

export const propertyFactory = Factory.Sync.makeFactory<RequiredBaseEntity<Property>>({
  __typename: 'Property',
  roof: null,
  view: null,
  cooling: null,
  style: null,
  area: null,
  bathsFull: null,
  bathsHalf: null,
  stories: null,
  fireplaces: null,
  flooring: null,
  heating: null,
  bathrooms: null,
  foundation: null,
  laundryFeatures: null,
  occupantName: null,
  ownerName: null,
  lotDescription: null,
  pool: null,
  subType: null,
  bedrooms: null,
  interiorFeatures: null,
  lotSize: null,
  areaSource: null,
  maintenanceExpense: null,
  additionalRooms: null,
  exteriorFeatures: null,
  water: null,
  lotSizeArea: null,
  subdivision: null,
  construction: null,
  lotSizeAreaUnits: null,
  type: null,
  garageSpaces: null,
  bathsThreeQuarter: null,
  accessibility: null,
  acres: null,
  occupantType: null,
  subTypeText: null,
  yearBuilt: null,
  parking: null,
});
